apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s" .Values.deployment.name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "adjustapi-apps.allLabels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.service.name}}
    port: {{ .Values.service.port | default "8000" }}
    targetPort: {{ .Values.service.targetPort | default "80" }}
    protocol: {{ .Values.service.protocol | default "TCP" }}
  type: {{ .Values.service.type }}
  selector:
    {{- toYaml .Values.service.selectorLabels | nindent 4 }}