# Default values for kafka-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: "default"
podSecurityContext: {}
securityContext: {}

#Specific values
cluster_name: local
environment: prod
type: test

imagePullSecrets: []

deployment:
  # enabled: true
  # image: 
  #   repository: hussainbani/adjustapi  
  #   tag: latest
  # name: adjustapi
  # replicaCount: 1
   
  # revisionHistoryLimit: 0
  # progressDeadlineSeconds: 600
  # rollingUpdate:
  #   maxSurge: 50%
  #   maxUnavailable: 0
  # resources:
  #   limits:
  #     cpu: 250m
  #     memory: 1024Mi
  #   requests:
  #     cpu: 250m
  #     memory: 512Mi
  # additionalVolumeMounts: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


service:
  #while only testing on local
  type: NodePort
  port: 8000

ingress:
  # annotations: {}
  #   # kubernetes.io/ingress.class: nginx
  #   # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: example.com
  #     paths:
  #       - path: /app
  #         pathType: ImplementationSpecific
  #       - path: /health
  #         pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

confimap:
  additionalLabels: {}

commonLabels: {}

additionalLabels: {}
