name: Reusable workflow to run golang test and linter, and build the image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASS:
        required: true
      DOCKER_REGISTRY:
        required: true

jobs:
  code-check:
    name: Running codechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          python-version: 3.8

      - name: run unit tests
        run: |
          make test

      - name: run linter
        run: |
          make lint
          
      - name: Run Bandit
        run: |
          make bandit

  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: [code-check]
    if: contains(needs.*.result, 'success')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          docker-version: '20.10.12'  # Use the desired Docker version

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t  $DOCKER_REGISTRY:$IMAGE_TAG -f Dockerfile .
          docker push $DOCKER_REGISTRY:$IMAGE_TAG
